# Generated by Django 6.0.5 on 2026-05-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_role_id_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program_type',
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.parent'),
        ),
        migrations.CreateModel(
            name='Attendance_Log',
            fields=[
                ('attendance_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='api.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_Log',
            fields=[
                ('audit_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=1000)),
                ('affected_table', models.CharField(max_length=1000)),
                ('record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('corresponding_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behavior_log', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_log', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Memorization_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('forgotten', models.BooleanField()),
                ('date', models.DateField()),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memorization_log', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorization_log', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reading_Log',
            fields=[
                ('reading_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reading_log', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_score', models.IntegerField()),
                ('reading_score', models.IntegerField()),
                ('review_score', models.IntegerField()),
                ('memorization_score', models.IntegerField()),
                ('attendance_score', models.IntegerField()),
                ('trimester', models.IntegerField()),
                ('date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_card', to='api.class')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report_card', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_review_log', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_log', to='api.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
