# Generated by Django 6.0.5 on 2026-05-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_enrollment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule_days',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
    ]
