# Generated by Django 6.0.5 on 2026-06-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_log',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='reading_log',
            name='student',
        ),
        migrations.RemoveField(
            model_name='review_log',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='review_log',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance_log',
            name='present',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surah', models.IntegerField()),
                ('ayah_init', models.IntegerField()),
                ('ayah_final', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField()),
                ('log_type', models.IntegerField()),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reading_log', to='api.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to='api.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Memorization_Log',
        ),
        migrations.DeleteModel(
            name='Reading_Log',
        ),
        migrations.DeleteModel(
            name='Review_Log',
        ),
    ]
