# Generated by Django 5.2.15 on 2026-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_behavior_log_id_alter_report_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='prorgram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
