# Generated by Django 5.2.15 on 2026-06-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_class_prorgram_class_room_class_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
