# Generated by Django 5.2.15 on 2026-06-13 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reading_log', to='api.class'),
        ),
    ]
