# Generated by Django 5.2.15 on 2026-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_log_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='behavior',
            field=models.IntegerField(default=5),
        ),
    ]
