# Generated by Django 5.2.15 on 2026-06-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_log_behavior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_card',
            name='logged_by',
        ),
    ]
