# Generated by Django 5.2.15 on 2026-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_report_card_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
    ]
