# Generated by Django 6.0.6 on 2026-07-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_behavior_log_id_alter_report_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='ayah_final',
        ),
        migrations.RemoveField(
            model_name='log',
            name='ayah_init',
        ),
        migrations.RemoveField(
            model_name='log',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='log',
            name='surah',
        ),
        migrations.CreateModel(
            name='QuranRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('log_type', models.IntegerField(blank=True, null=True)),
                ('surah', models.PositiveSmallIntegerField()),
                ('ayah_init', models.PositiveSmallIntegerField()),
                ('ayah_final', models.PositiveSmallIntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='api.log')),
            ],
        ),
    ]
