# Generated by Django 6.0.6 on 2026-07-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_log_ayah_final_remove_log_ayah_init_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranrange',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quran_ranges', to='api.student'),
        ),
    ]
