# Generated by Django 6.0.6 on 2026-07-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_quranrange_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranrange',
            name='student',
        ),
    ]
