# Generated by Django 6.0.6 on 2026-07-09 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_quranrange_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='corresponding_user',
        ),
        migrations.AlterField(
            model_name='behavior_log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance_log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report_card',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='corresponding_user',
        ),
        migrations.AlterField(
            model_name='behavior_log',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behavior_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='prorgram',
            new_name='program',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.JSONField(blank=True, null=True, verbose_name=list),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.JSONField(null=True, verbose_name=list),
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.JSONField(blank=True, null=True, verbose_name=list),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
